function displayLyrics(response) {
  let songGeneratedElement = document.querySelector("#song-generating");
  songGeneratedElement.innerHTML = "💜 Give this song a listen:";

  new Typewriter("#song-lyrics", {
    strings: response.data.answer,
    autoStart: true,
    delay: 5,
    cursor: "",
  });

  // HOW DO I GET THE DISCLAIMER TO ONLY SHOW UP AFTER THE TYPEWRITER IS FINISHED???
  // let disclaimerElement = document.querySelector("#disclaimer");
  // disclaimerElement.innerHTML = "<strong>Disclaimer:</strong>\nThe song descriptions and lyrics provided are generated by <strong>SheCodes AI</strong> and may not be entirely accurate or reflective of the original content. The AI-generated content is for entertainment and informational purposes only and should not be considered as a definitive source of information. Users are encouraged to verify the accuracy and authenticity of the generated content independently."
}

function generateSong(event) {
  event.preventDefault();

  let instructionsInput = document.querySelector("#user-instructions");
  let apiKey = "0a140ebb07f1ea6t77816o3e4ffa1319";
  let context =
    "As an AI assistant, you are equipped with extensive knowledge about the South Korean boy band known as Bangtan Boys, or BTS. Your expertise encompasses their entire discography, including lyrics and the deeper meanings embedded within. Please provide the information in basic HTML format as follows: <strong>Song Title</strong><br />YouTube URL (make sure this is written out as URL and can open in a new tab)<br /><br /><strong>Description: </strong>(write the description of the song theme here)<br /><br /><strong>Lyrics: </strong><br />(provide 10 lines of the song lyrics here and <br /> for every lyric line) Crucial instructions: Do not include bullet points, list numbers, or quotation marks on the lyrics. Make sure to provide the lyrics in English. Do not include suggestive words or phrases. Please only follow the basic HTML format as written above.";
  let prompt = `Recommend a BTS song that is about ${instructionsInput.value}.`;
  let apiUrl = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

  let lyricsContainer = document.querySelector("#lyrics-container");
  lyricsContainer.classList.remove("hidden");

  // TYPING ANIMATION - HOW DO I GET THIS STRING TO TYPE OUT INFINITELY WITHOUT BEING DELETED BACKWARDS??
  let songGenerating = document.querySelector("#song-generating");
  songGenerating.innerHTML = `⏳ <span id="generating">Generating song...</span>`;

  // TRIED THIS AND DID NOT WORK EITHER
  // new Typewriter("#generating", {
  //   strings: "Generating song...",
  //   autoStart: true,
  //   delay: 1,
  //   deleteSpeed: Infinity,
  //   cursor: "",
  // })

  axios.get(apiUrl).then(displayLyrics);
}

// HOW DO I GET THE LYRICS-CONTAINER TO CLEAR OR HIDE WHEN generateSong() IS RUN AGAIN??

let songFormElement = document.querySelector("#song-lyrics-form");
songFormElement.addEventListener("submit", generateSong);
